-- CreateTable
CREATE TABLE "PublishSettings" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "dailyLimit" INTEGER NOT NULL DEFAULT 1
);
